export const CAMPAIGN_CONFIG = [
  {
    id: "san-valentin",
    name: "San Valentín",
    icon: "❤️",
    color: "rosado",
    colorClass: "catalog-campaign-pink",
    priority: 100,
  },
  {
    id: "dia-mujer",
    name: "Día de la Mujer",
    icon: "🌷",
    color: "fucsia",
    colorClass: "catalog-campaign-fuchsia",
    priority: 95,
  },
  {
    id: "dia-madre",
    name: "Día de la Madre",
    icon: "💐",
    color: "lavanda",
    colorClass: "catalog-campaign-lavender",
    priority: 90,
  },
  {
    id: "dia-padre",
    name: "Día del Padre",
    icon: "👔",
    color: "azul",
    colorClass: "catalog-campaign-blue",
    priority: 85,
  },
  {
    id: "graduados",
    name: "Graduados",
    icon: "🎓",
    color: "morado",
    colorClass: "catalog-campaign-purple",
    priority: 80,
  },
  {
    id: "flores-amarillas",
    name: "Flores Amarillas",
    icon: "🌻",
    color: "amarillo",
    colorClass: "catalog-campaign-yellow",
    priority: 75,
  },
  {
    id: "hotwheels",
    name: "Hot Wheels",
    icon: "🏎️",
    color: "rojo",
    colorClass: "catalog-campaign-red",
    priority: 70,
  },
] as const;

export type CampaignId = (typeof CAMPAIGN_CONFIG)[number]["id"];
